name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (without v)'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Update manifest.json and package.json
        run: |
          VERSION=${{ github.event.inputs.version }}

          echo "Updating manifest.json to $VERSION"
          jq --arg v "$VERSION" '.version = $v' manifest.json > manifest.tmp && mv manifest.tmp manifest.json

          echo "Updating package.json to $VERSION"
          jq --arg v "$VERSION" '.version = $v' package.json > package.tmp && mv package.tmp package.json

      - name: Commit changes
        run: |
          VERSION=${{ github.event.inputs.version }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest.json package.json
          git commit -m "chore: release v$VERSION"
          git push origin HEAD

      - name: Create tag
        run: |
          VERSION=${{ github.event.inputs.version }}
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
